discord_token = "your discord bot token" # Required
chain_storage_dir = "/the/directory/where/chains/shoul/be/stored" # Required

# Settings specific to generating the markov chains. This whole section can be omitted, meaning defaults will be used.
[generation]
min_words = 2 # The minimum length of a message in order to be included in markov chain generation. Defaults to 1.
include_tag_only = false # Should messages that only contain a mention be included? Defaults to true.
